---
title: "About"
output: html_document
---

I am a Ph.D. student working on Human-Computer Interaction (HCI) and Virtual Realty (VR) research at TU Darmstadt, Germany, previously in the [DIVA Group](https://diva.telecom-paristech.fr/) at Telecom Paris, France.

VR induces a dual-environment paradigm where the virtual space overlays the real-world surroundings. VR participants are visually disconnected from their real-world environment. New safety challenges emerge when people can use VR everywhere, like their homes, which are usually less controlled. My current research interest focuses on understanding people's cognitive and behavioral processes in the dual-environment paradigm from the VR perspective. Please see [Projects](https://wenjietseng.com/wjiesite/projects.html) to know more.

I finished my Master's degree at National Chiao Tung University, Taiwan, exploring how to integrate input controls and haptic outputs with VR head-mounted displays.
<!-- [CV](/assets/pdf/WJT_CV.pdf)  -->

<!-- This site is inspired by the following rmarkdown websites: [LabJournal from CrumpLab](https://github.com/CrumpLab/LabJournalWebsite) and [privefl](https://github.com/privefl/rmarkdown-website-template?tab=readme-ov-file). -->