---
title: "Exercise: Hand Redirection in VR"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 2
---

This exercise is for the class, Haptic and Applications (17.11.2025), in IA pour l’ADAPTation d’environnements multimodaux (UM5IN258 - S1-25) at Sorbonne Université.

# Prerequisite

By following this tutorial, you can set up the Unity project for the exercise.

## Hardware

- We have 8 Quests, so that 3-4 students share one. It would be great if you can make sure that your team has one powerful Windows computer for the Quest link.
- Each Quest comes with two controllers with batteries and one USB C cable (for the Quest link or building the apk). If your controllers run out of battery, we have extra ones for your to exchange.
- The Quests are already in developer mode. This [tutorial](https://developers.meta.com/horizon/documentation/unity/unity-env-device-setup) is a reference about how to set up developer mode.
- Once the exercise ends (~17h00), please put everything in the case and return them to Amel.

## Software

- For this exercise, we use [Unity **2020.3** LTS](https://unity.com/download) because our project is based on an older version of Oculus XR plugin.
  - We often need to download and manage packages/libraries (for example, Meta SDK for developing Quest). To make our life easier in this exercise, please use [**this link**](https://drive.google.com/file/d/1upSOI9eQInjHFAIj8nMpqvViTV-MI840/view?usp=sharing).
  - You can consider installing Android Build Support for your Unity if you don't have a windows computer.
  - [Set up Unity for VR development](https://developers.meta.com/horizon/documentation/unity/unity-project-setup): This page explains the compatibility of two XR plugins, Oculus XR (legacy) and Unity Open XR (future).
- [Meta Quest link](https://developers.meta.com/horizon/documentation/unity/unity-link/) (highly recommended): If you use a Windows computer with a good graphic card, you can set up the Quest link to make the VR development on Unity easier.
- Building apk is another way to develop VR in Unity, but painful. To avoid that in our 1.5 hrs exercise, I will set up a Windows computer for those who need it.
- [SideQuest](https://sidequestvr.com/) allows you to install your apk to the Quest. SideQuest also provides broadcast view while using VR.
- [Meta Quest XR Simulator](https://developers.meta.com/horizon/documentation/unity/xrsim-getting-started): This is a new tool provided by Meta. I haven't tried but perhaps it's worth a shot for non-Windows users.

## Demo video

<center><iframe width="560" height="315" src="https://www.youtube.com/embed/R9r0cTbWFi4?si=GKqsOOHw-woYNH7W" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></center>

I added some VR controller input in `ExperimentRedirectionHand.cs` and `CalibrationOnStart.cs` (see `Update()` in both scripts). On the left controller, Button X is for calibration, and the joystick is for adjusting $\theta$ (the angular difference between the virtual and real hands). On the right controller, Button B is for showing the real hand, and Button A is for starting one trial. 

# Problems

## Warm-up

1. Run the project on Unity:
  - If you have a powerful Windows computer, you could set up the [Meta Quest link](https://developers.meta.com/horizon/documentation/unity/unity-link/).

  <!-- - (optional) Build the apk to your Quest ([Tutorial](https://developers.meta.com/horizon/documentation/unity/unity-project-configuration)) -->

2. Calibration: We often calibrate the virtual scene with the physical environment when using VR, especially when we need to align two spaces (not in this exercise though). Find the script and check how to calibrate. If you are interested, you can look into `calib2()` and `CalibrationTool.CalibrateFromTag()` functions to see what is the difference. Discuss with you teammates.
3. Assign the calibration to another input mapping on the left controller ([Tutorial](https://developers.meta.com/horizon/documentation/unity/unity-ovrinput/))
4. Let's play around with $\theta$ by decreasing and increasing the angular difference between your virtual and real hand. Discuss the difference that you observe with your teammates.

## Basic

Please read all the problems and decide which one you want to do. The order is arbitrary.

5. We can manipulate the offset from $X$, $Y$, and $Z$. Design hand redirection in a different axis. First discuss with your teammate about how to implement each of them. Next, pick one axis to implement it.
6. Fix the offset at the same value and compare hand redirection in different axes. Discuss which direction is easier to detect.
7. Fix the offset at the same value and play around with the gain functions. Again, what are the differences?
8. Extend the setup into a block - repeating 10 times with randomized offsets. By repeating several blocks, you can collect data for drawing a psychometric function.
9. Implement the code to record data (the answer and $\theta$ of each trial). Plot the psychometric function and discuss what's the difference between each teammate.
10. Record the trajectory of physical hand in each trial. Plot the data and discuss the difference between each teammate.

## Open-ended

For these problems, there is no simple and quick answers. Please first discuss with your teammates about how to solve the problem before implement it.

11. Imagine there are multiple virtual targets. The system does not know in advance which object the participant will touch. How can the system adapt accordingly?
12. Instead of using controllers, adapt this implementation to hand tracking.
13. Instead of reaching the virtual sphere floating in mid-air, use a real physical object. What are the challenges? Hint: this requires calibration. 
13. Instead of offsetting the virtual hand position using $\theta$, achieve hand redirection by rotating the virtual environment.